# Generated by Django 3.1.6 on 2021-07-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('base_unit', models.CharField(max_length=50)),
                ('type_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_app', to='tests_app.type_test')),
            ],
            options={
                'verbose_name': 'Испытание',
                'verbose_name_plural': 'Испытания',
                'ordering': ('name',),
            },
        ),
    ]
