# Generated by Django 3.1.6 on 2021-07-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_Test',
            new_name='TestType',
        ),
        migrations.AlterModelOptions(
            name='testtype',
            options={'ordering': ('name',), 'verbose_name': 'Тип испытаний', 'verbose_name_plural': 'Типы испытаний'},
        ),
    ]
