# Generated by Django 3.1.6 on 2021-07-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=100, null=True)),
                ('elem_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('elem_group_count', models.IntegerField(default=0)),
                ('count_elem', models.IntegerField(default=0)),
                ('size_elem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='cables.category')),
            ],
            options={
                'verbose_name': 'Кабель',
                'verbose_name_plural': 'Кабели',
                'ordering': ('mark',),
            },
        ),
    ]
