# Generated by Django 3.1.6 on 2021-08-08 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
